### ISSUE TITLE
Restore style rules from CakePHP 2 version of site

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/commentaries_cake3#10]
Things that have lost their styling:
- [x] The "Recent" section of the sidebar
- [x] The "Top Tags" section of the sidebar (table width, text alignment, text-transform)
- [x] The "About the Author" section (`div.profile_box`)
- [x] The subsections of `#tag_list` (the cloud vs. list switcher should be more distinct from the actual collection of tags, but now might be a good opportunity to come up with a better design than my circa-2013 one)
- [x] The vertical-align of `#tag_cloud a`
- [x] `h1.page_title`
- [x] `table.commentaries`
- [x] `h3.title` (Commentary titles)
- [x] `.commentary_years` (though now that we can't fit all years on one line, it might be a good opportunity to come up with a better design)

(I may have more notes for the admin parts of the site, ~~but I can't currently access them, as the credentials that I use to log in to the CakePHP 2 version of the site don't work for this version~~)

**Comment by ericadeefox** [comment]
> the credentials that I use to log in to the CakePHP 2 version of the site don't work for this version

oh no. they should... I just went through this making sure they had the same salts and a working rehasher and everything. It was tested for this, argh...

**Comment by ericadeefox** [comment]
Actually, would you mind attaching a screencap on here of what the front page of the site looks like on your end?

**Comment by PhantomWatson** [comment]
![c04ad042-7510-4f02-b511-50ee2c30b166](https://user-images.githubusercontent.com/1965565/34119560-8d55a456-e3f0-11e7-8e66-69a5729fbd20.png)

**Comment by ericadeefox** [comment]
aww damn that's what I thought... yeah, here's mine:

![image](https://user-images.githubusercontent.com/12422542/34119583-a928f43a-e3f0-11e7-869d-f33023f9e041.png)

I got all the styling errors you're seeing on your end, when I fiddled with the Datacenter plugin so that it'd look for datacenter.css rather than style.css.

**Comment by PhantomWatson** [comment]
`datacenter.less` is only [`@import`ed when each site's `style.less` is compiled into `style.css`](https://github.com/BallStateCBER/commentaries_cake3/blob/master/webroot/css/style.less#L4) and not compiled/loaded directly, so there shouldn't be any `datacenter.css` for the plugin to look for.

**Comment by ericadeefox** [comment]
I meant datacenter.cake2.css, my mistake

**Comment by ericadeefox** [comment]
![dropdownyear](https://user-images.githubusercontent.com/12422542/34168533-bc11a0d4-e4b2-11e7-9e43-e9095cad4049.gif)

How's this for a solution to the Too Many Years problem?

**Comment by PhantomWatson** [comment]
Very good! The only improvement that I can think of is making "Select a year" the `<label>` for that `<select>`. Maybe with the arrow character changed to `<span class="glyphicon glyphicon-arrow-right">` or just a colon.

**Comment by ericadeefox** [comment]
![cloudvslist](https://user-images.githubusercontent.com/12422542/34169439-6b5bbd70-e4b5-11e7-8500-56782d10b4ae.gif)

[shrug] Togglers always get me. Lemme see if I can find a toggler that's an actual switch that one could slide or something to that effect.

**Comment by ericadeefox** [comment]
![toggle buttonz](https://user-images.githubusercontent.com/12422542/34169992-3bdd60c4-e4b7-11e7-90c2-2f54e89d8e02.gif)

A little more in-your-face I suppose...

**Comment by ericadeefox** [comment]
> The only improvement that I can think of is making "Select a year" the `<label>` for that `<select>`. 

Right, or else screen readers will get confused and their users will get irritated

**Comment by ericadeefox** [comment]
^^I can do that right quick. It's just some different math.

**Comment by PhantomWatson** [comment]
Here's how I did it for Muncie Events: https://github.com/BallStateCBER/muncie_events/blob/development/app/View/Tags/index.ctp#L143

**Comment by ericadeefox** [comment]
![fanciest togglers](https://user-images.githubusercontent.com/12422542/34171305-dcec2028-e4bb-11e7-9240-909909774f7a.gif)

friendly togglers and sensible font sizes +1 +1 +1

**Comment by ericadeefox** [comment]
![yes](https://user-images.githubusercontent.com/12422542/34171375-1f804338-e4bc-11e7-8033-6aec8e113f76.gif)

here we are
