### ISSUE TITLE
/users/my-account form features missing

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/commentaries_cake3#14]
The "My Profile" form has lost its password-changing component and the ability to leave one's sex unspecified.

Styling sidenotes:
- A `<select>` form for sex and an accompanying label would be preferred, but if we're switching it to a set of radio buttons, they should each be on separate lines with some space between the button and its label
- The submit button should be embiggened and defaultified

**Comment by ericadeefox** [comment]
Question: why do we need to know the sex of our user base?

**Comment by PhantomWatson** [comment]
I think that was requested back in the day so that when CBER staffers talk about members of the newsmedia with ambiguous first names, we know what pronoun to use. And I think there was a vague idea of someday having the site use the proper pronoun when referring to a user's actions. But it's not critical (and there's the whole nonbinary thing), so that field was made nullable.

**Comment by ericadeefox** [comment]
Could we do a text input box (instead of radio buttons or dropdown) with "gender" instead? I'll write the migration for it and everything. Just don't want to leave anyone out here.

**Comment by PhantomWatson** [comment]
We could, but I can think of no scenario that wouldn't be covered by the current approach of allowing male, female, and null for `Users.sex`.

**Comment by PhantomWatson** [comment]
The ability to change one's password still needs to be added to the administrators' "My Account" page.

**Comment by ericadeefox** [comment]
Added & tested :+1:
