### ISSUE TITLE
My Account form isn't saving

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/commentaries_cake3#16]
Some weirdness:
- The `Users.bio` field doesn't seem to actually be sent, as it doesn't appear in `$_REQUEST`
- The `Users.gender` field in `$user` doesn't appear to be updated by `patchEntity()` despite it being in the results of `getData()`
  I'm not sure what the cause could be, since `User::_accessible['*'] = true`

**Comment by ericadeefox** [comment]
Just making sure: you ran the new migration??

**Comment by PhantomWatson** [comment]
I absolutely did not. 😟

**Comment by ericadeefox** [comment]
Yea my tests were failing too then I remembered I hadn't updated them for the migration. Once the migration is run, everything works. But that doesn't explain this bio thing. And its insolence.

**Comment by PhantomWatson** [comment]
Yeah, nevermind about the gender thing, but the bio still isn't getting sent to the server.

**Comment by ericadeefox** [comment]
Yeah, there's something weird with the ckeditor plugin. I don't know why but, on my end, it keeps sending the email address as the bio

**Comment by ericadeefox** [comment]
WEIRD NEW TWIST OF THINGS: it has the same problem in the add form too, but the edit form works fine?
